### ISSUE TITLE
nowa init升级之后使用了refast，原先使用的是reflux，怎么办

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa-init#17]
之前nowa init page出来的是reflux结构：
![image](https://cloud.githubusercontent.com/assets/7553998/26348741/3f963ec4-3fe0-11e7-9ca2-05cb4cc47860.png)
现在变成了refast
![image](https://cloud.githubusercontent.com/assets/7553998/26348751/4764f992-3fe0-11e7-81d6-52136061b3e6.png)
请问怎么改回去？

**Comment by fengsx** [comment]
refast减少了概念，降低了文件的维护。让数据的变动流向更为清晰。建议您尝试。

- 如果您需要降级到reflux可以使用v1或者v2或者v3版本的的uxcore初始化您的项目：
```
nowa init https://github.com/nowa-webpack/template-uxcore/archive/[版本号v1、v2或者v3].zip -a uxcore
```
然后使用nowa init page生成的就是使用了reflux的页面。

- 如果项目已经生成了，如果您使用mac或者linux可以这么修改：
```
> cd ~/.nowa/init
> vi alias.json
```
将uxcore对应的版本改为v1、v2 或者 v3 即可。
