### ISSUE TITLE
关于publicPath的配置问题

### ISSUE THREAD

**Issue by fengsx** [nowa-webpack/nowa-init#8]
我现在的publicPath开发和build的时候不太一样：
1、如果我是用nowa server，那么我希望publicPath是 / 这个现在是默认的，没问题
2、如果我nowa build的时候，我希望能够配置publicPath

我看文档里有覆写webpack.config.js的功能。我的配置如下：

```
module.exports = function (config) {
  // 传入 config 为默认 webpack 配置
  config.output.chunkFilename = '[name].js';
  // 修改发布地址
  // config.output.publicPath = '//daily.mydomain.net/myproject/';
};

```
每次nowa server 或者nowa build的时候，我都需要改发布地址。这个有没有什么自动化的办法？比如给上面的返回函数加一个参数，表示现在是server还是build？

**Comment by gbk** [comment]
试试
`process.argv[2] === 'server'`

**Comment by fengsx** [comment]
非常棒！感谢啦
